steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-f'
      - 'apps/worker/Dockerfile'
      - '-t'
      - 'europe-west1-docker.pkg.dev/banklens-prod/banklens/worker'
      - '.'

images:
  - 'europe-west1-docker.pkg.dev/banklens-prod/banklens/worker'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
